#服务器端口
server:
  port: 8200

#数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${blade.datasource.test.url}
    username: ${blade.datasource.test.username}
    password: ${blade.datasource.test.password}

#配置日志地址
logging:
  config: classpath:log/logback_${blade.env}.xml
#第三方登陆
social:
  enabled: true
  domain: http://127.0.0.1:1888
